// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: glnro/random_oracle/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRandomRoundRequest struct {
	Round uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *QueryRandomRoundRequest) Reset()         { *m = QueryRandomRoundRequest{} }
func (m *QueryRandomRoundRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRandomRoundRequest) ProtoMessage()    {}
func (*QueryRandomRoundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca01f327fdb9588, []int{0}
}
func (m *QueryRandomRoundRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomRoundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomRoundRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomRoundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomRoundRequest.Merge(m, src)
}
func (m *QueryRandomRoundRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomRoundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomRoundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomRoundRequest proto.InternalMessageInfo

func (m *QueryRandomRoundRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type QueryRandomRoundResponse struct {
	RandomResult *RandomResult `protobuf:"bytes,1,opt,name=random_result,json=randomResult,proto3" json:"random_result,omitempty"`
}

func (m *QueryRandomRoundResponse) Reset()         { *m = QueryRandomRoundResponse{} }
func (m *QueryRandomRoundResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRandomRoundResponse) ProtoMessage()    {}
func (*QueryRandomRoundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bca01f327fdb9588, []int{1}
}
func (m *QueryRandomRoundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomRoundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomRoundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomRoundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomRoundResponse.Merge(m, src)
}
func (m *QueryRandomRoundResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomRoundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomRoundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomRoundResponse proto.InternalMessageInfo

func (m *QueryRandomRoundResponse) GetRandomResult() *RandomResult {
	if m != nil {
		return m.RandomResult
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRandomRoundRequest)(nil), "glnro.random_oracle.v1.QueryRandomRoundRequest")
	proto.RegisterType((*QueryRandomRoundResponse)(nil), "glnro.random_oracle.v1.QueryRandomRoundResponse")
}

func init() { proto.RegisterFile("glnro/random_oracle/v1/query.proto", fileDescriptor_bca01f327fdb9588) }

var fileDescriptor_bca01f327fdb9588 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x57, 0x71, 0x1e, 0x32, 0x45, 0x2c, 0x03, 0x67, 0xe7, 0x8a, 0x4c, 0x84, 0xa9, 0xd0,
	0xd0, 0x79, 0xf0, 0xbe, 0x6f, 0x60, 0x8f, 0x1e, 0x1c, 0xe9, 0x16, 0x62, 0xa1, 0xcd, 0xeb, 0x92,
	0x74, 0x30, 0xc4, 0x8b, 0x5f, 0x40, 0xc1, 0x93, 0xdf, 0xc8, 0xe3, 0xc0, 0x8b, 0x47, 0xd9, 0xfc,
	0x20, 0xd2, 0x24, 0x85, 0xb9, 0x21, 0x78, 0x69, 0xf3, 0x7f, 0xef, 0xf7, 0xde, 0x3f, 0xf9, 0xa3,
	0x36, 0x4b, 0xb9, 0x00, 0x0c, 0x82, 0x8c, 0x52, 0x8a, 0xa7, 0x21, 0x9e, 0x14, 0x54, 0xcc, 0x82,
	0x5c, 0x80, 0x02, 0x77, 0x5f, 0x37, 0x03, 0xd3, 0x0c, 0xa6, 0xa1, 0x77, 0xcc, 0x00, 0x58, 0x4a,
	0x31, 0xc9, 0x13, 0x4c, 0x38, 0x07, 0x45, 0x54, 0x02, 0x5c, 0x1a, 0xdc, 0xbb, 0x18, 0x81, 0xcc,
	0x40, 0xe2, 0x98, 0x48, 0x6a, 0xf6, 0xe0, 0x69, 0x18, 0x53, 0x45, 0x42, 0x9c, 0x13, 0x96, 0x70,
	0x0d, 0x5b, 0xb6, 0x6d, 0xd9, 0x0a, 0x5b, 0xf5, 0xf5, 0x8e, 0x4c, 0x73, 0xa8, 0x15, 0x36, 0xc2,
	0xb6, 0x9a, 0x0c, 0x18, 0x98, 0x7a, 0x79, 0xb2, 0xd5, 0x03, 0x92, 0x25, 0x1c, 0xb0, 0xfe, 0x56,
	0x06, 0xeb, 0x0f, 0x53, 0xb3, 0x9c, 0xda, 0x2d, 0x5d, 0x8c, 0x0e, 0x6f, 0x4a, 0xbf, 0x88, 0xf0,
	0x31, 0x64, 0x11, 0x14, 0x7c, 0x1c, 0xd1, 0x49, 0x41, 0xa5, 0x72, 0x9b, 0xa8, 0x2e, 0x4a, 0xdd,
	0x72, 0x4e, 0x9c, 0xde, 0x76, 0x64, 0x44, 0xf7, 0x0e, 0xb5, 0x36, 0x07, 0x64, 0x0e, 0x5c, 0x52,
	0x77, 0x80, 0xf6, 0x84, 0x2e, 0x0f, 0x05, 0x95, 0x45, 0xaa, 0xf4, 0x64, 0xa3, 0xdf, 0x09, 0xd6,
	0xd2, 0x0b, 0xec, 0xb0, 0x86, 0xa2, 0x5d, 0xb1, 0xa2, 0xfa, 0x6f, 0x0e, 0xaa, 0x6b, 0x03, 0xf7,
	0xd9, 0x41, 0x8d, 0x15, 0x17, 0xb7, 0xb7, 0xb1, 0xe6, 0x8f, 0x9b, 0x7b, 0xe7, 0xff, 0x20, 0xcd,
	0x95, 0xbb, 0x97, 0x4f, 0x1f, 0xdf, 0xaf, 0x5b, 0x67, 0xee, 0xa9, 0x0d, 0xb7, 0x8a, 0xa9, 0x7a,
	0x47, 0x09, 0xe3, 0x07, 0xfd, 0x7b, 0x1c, 0x5c, 0xbf, 0x2f, 0x7c, 0x67, 0xbe, 0xf0, 0x9d, 0xaf,
	0x85, 0xef, 0xbc, 0x2c, 0xfd, 0xda, 0x7c, 0xe9, 0xd7, 0x3e, 0x97, 0x7e, 0xed, 0xb6, 0xc3, 0x12,
	0x75, 0x5f, 0xc4, 0xc1, 0x08, 0x32, 0xfc, 0x2b, 0x6e, 0x9d, 0x75, 0xbc, 0xa3, 0xc3, 0xbe, 0xfa,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x3d, 0x3e, 0x06, 0x64, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	RandomRound(ctx context.Context, in *QueryRandomRoundRequest, opts ...grpc.CallOption) (*QueryRandomRoundResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) RandomRound(ctx context.Context, in *QueryRandomRoundRequest, opts ...grpc.CallOption) (*QueryRandomRoundResponse, error) {
	out := new(QueryRandomRoundResponse)
	err := c.cc.Invoke(ctx, "/glnro.random_oracle.v1.Query/RandomRound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	RandomRound(context.Context, *QueryRandomRoundRequest) (*QueryRandomRoundResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) RandomRound(ctx context.Context, req *QueryRandomRoundRequest) (*QueryRandomRoundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomRound not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_RandomRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glnro.random_oracle.v1.Query/RandomRound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomRound(ctx, req.(*QueryRandomRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "glnro.random_oracle.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RandomRound",
			Handler:    _Query_RandomRound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "glnro/random_oracle/v1/query.proto",
}

func (m *QueryRandomRoundRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomRoundRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomRoundRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomRoundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomRoundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomRoundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RandomResult != nil {
		{
			size, err := m.RandomResult.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRandomRoundRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Round != 0 {
		n += 1 + sovQuery(uint64(m.Round))
	}
	return n
}

func (m *QueryRandomRoundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RandomResult != nil {
		l = m.RandomResult.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRandomRoundRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomRoundRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomRoundRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomRoundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomRoundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomRoundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RandomResult", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RandomResult == nil {
				m.RandomResult = &RandomResult{}
			}
			if err := m.RandomResult.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
